version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: atro_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atro_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: atro_backend_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/atro_db?schema=public
      - JWT_SECRET=atro_jwt_secret_key_2026_super_secure
      - GEMINI_API_KEY=AIzaSyATLZNLQwLfXAMBBAMJsBgZaaaL4XD9n5s
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads

volumes:
  pgdata:
  uploads_data:
