-- AlterTable
ALTER TABLE "User" ADD COLUMN "businessType" TEXT DEFAULT '3';
ALTER TABLE "User" ADD COLUMN "revenueGoal" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "staffSize" INTEGER DEFAULT 0;
